tunnel: bskp-tunnel
credentials-file: /etc/cloudflared/bskp-tunnel.json

ingress:
  # Zabbix Server TCP
  - hostname: zbxproxy.blackskulp.com.br
    service: tcp://192.168.0.20:10051

  # Zabbix Frontend
  - hostname: zbx.blackskulp.com.br
    service: http://192.168.0.20:8080

  # Grafana
  - hostname: grafana.blackskulp.com.br
    service: http://192.168.0.30:3000

  # Intranet (via Nginx port 81)
  - hostname: intranet.blackskulp.com.br
    service: http://192.168.0.25:81

  # Default
  - service: http_status:404
