tunnel: bb479f0d-e056-4e6e-9984-ddfa5d7bcefb
credentials-file: /etc/cloudflared/bb479f0d-e056-4e6e-9984-ddfa5d7bcefb.json
origincert: /etc/cloudflared/cert.pem

ingress:
  - hostname: zbx.blackskulp.com.br
    service: http://192.168.0.20:4080

  - hostname: haos.blackskulp.com.br
    service: http://192.168.0.35:8123

  - hostname: grafana.blackskulp.com.br
    service: http://192.168.0.20:6080

  - hostname: proxy.blackskulp.com.br
    service: https://192.168.0.20:81
    originRequest:
      noTLSVerify: true
      httpHostHeader: proxy.blackskulp.com.br

  - hostname: portainer.blackskulp.com.br
    service: https://192.168.0.20:9443
    originRequest:
      noTLSVerify: true
      httpHostHeader: portainer.blackskulp.com.br

  - hostname: pve.blackskulp.com.br
    service: https://192.168.0.10:8006
    originRequest:
      noTLSVerify: true
      httpHostHeader: pve.blackskulp.com.br

  - hostname: zbxproxy.blackskulp.com.br
    service: tcp://172.18.0.35:10051

  - service: http_status:404
