services:
  ctr-nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${VOL_CONF}
      - ${VOL_TZ}
      - ${VOL_LOCALTIME}
    ports:
      - "81:80"
    networks:
      network-share:
        ipv4_address: ${IPV4_NGINX}

networks:
  network-share:
    external: true
