services:
  ctr-laravel12:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST_HTTP_PORT}:8000"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      TIMEZONE: ${TIMEZONE}
      WORKDIR: ${WORKDIR}
      LARAVEL_VERSION: ${LARAVEL_VERSION}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - ${VOL_APP}
      - ${VOL_MYSQL}
      - ${VOL_TIMEZONE}
      - ${VOL_LOCALTIME}
    networks:
      network-share:
        ipv4_address: ${IPV4_ADDRESS}

networks:
  network-share:
    external: true
