services:
  unifi:
    image: jacobalberty/unifi
    container_name: srv-unifi
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
      - 3478:3478/udp
      - 8880:8880
    volumes:
      - /bskp/srv-unifi:/unifi
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.default.disable_ipv6=1
    networks:
      network-share:
        ipv4_address: 172.18.0.8
networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
