services:
  ctr-fasternet:
    build: .
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${VOL_SCRIPT}
      - ${VOL_CRON}
      - ${VOL_TIMEZONE}
      - ${VOL_LOCALTIME}
    command: ["cron", "-f"]
    networks:
      network-share:
        ipv4_address: ${IPV4_ADDRESS}

networks:
  network-share:
    external: true
